# Generated by Django 4.1 on 2022-10-27 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articles_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('artc_place', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='articles.articles')),
            ],
        ),
    ]
