# Generated by Django 4.1 on 2022-11-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_price', models.FloatField()),
                ('item_picture', models.ImageField(blank=True, null=True, upload_to='upload/')),
            ],
        ),
    ]
