# Generated by Django 4.1.3 on 2022-11-02 15:57

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('goods_catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnxietyBoost',
            fields=[
                ('catalogue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='goods_catalogue.catalogue')),
                ('boostrate', models.IntegerField()),
            ],
            bases=('goods_catalogue.catalogue',),
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SoulComforter',
            fields=[
                ('catalogue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='goods_catalogue.catalogue')),
                ('max_comfort', models.IntegerField()),
            ],
            bases=('goods_catalogue.catalogue',),
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='catalogue',
            old_name='item_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='catalogue',
            old_name='item_picture',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='catalogue',
            old_name='item_price',
            new_name='price',
        ),
    ]
