# Generated by Django 4.1 on 2022-12-12 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods_catalogue', '0002_anxietyboost_soulcomforter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogue',
            old_name='picture',
            new_name='image',
        ),
    ]
