# Generated by Django 4.1 on 2022-12-12 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods_catalogue', '0003_rename_picture_catalogue_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnxietyBoost',
            new_name='HappinessBoost',
        ),
        migrations.RenameField(
            model_name='soulcomforter',
            old_name='max_comfort',
            new_name='comfortrate',
        ),
    ]
