# Generated by Django 4.1 on 2022-10-31 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('posts_index', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='forum.posts')),
            ],
        ),
    ]
