# Generated by Django 4.1 on 2022-10-31 02:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mh_tests', '0003_alter_mentaltest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentaltest',
            name='date',
            field=models.DateTimeField(default=datetime.date(2022, 10, 31)),
        ),
    ]
