# Generated by Django 4.1 on 2022-10-29 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_events', '0003_delete_user_alter_event_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_joined',
            field=models.BooleanField(default=False),
        ),
    ]
