# Generated by Django 4.1 on 2022-10-29 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_image_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
    ]
